### ISSUE TITLE
Add documentation about default limits for API responses

### ISSUE THREAD

**Issue by pcraig3** [cds-snc/nrcan_api#448]
So we have not included a default limit in our API response, but we're using [`mongo-cursor-pagination`](https://www.npmjs.com/package/mongo-cursor-pagination) to return paginated data, and it's setting a default limit for us of 50 results. 
It's also setting a maximum number of responses (regardless of whatever is passed in) of 300.
We can override that ourselves, but we haven't done.

I read that here: https://www.npmjs.com/package/mongo-cursor-pagination#number-of-results

It's not documented in our API, but it should be. Otherwise this will give surprising results.

**Comment by evadb** [comment]
This is now documented, closing 👍

**Comment by pcraig3** [comment]
@obrien-j, Yeah, there's an environment variable we can set to override the default limit of 300, but we haven't done it.

I don't think there's a particular reason why not. We would probably want to add our own default if we did (otherwise, all queries with no explicit `limit` would return the entire dataset), but in principle I don't think there would be an issue.

**Comment by evadb** [comment]
If we're discussing adding a new feature or modifying, maybe opening a new issue is best? This issue has been covered

**Comment by pcraig3** [comment]
👍
