### ISSUE TITLE
Generate and populate open data set with the open.canada.ca platform

### ISSUE THREAD

**Issue by obrien-j** [cds-snc/nrcan_api#467]

**Comment by obrien-j** [comment]
Just got an account created on open.canada.ca registry platform. Testing out what would be required to setup records to be able to publicly expose the api in a standard fashion. 

Confirmed we can port this record from TBS department to NRCan Open Data registry.

**Comment by sdkibb** [comment]
NRCan will be handling the OD submission. They'll need to document and get approvals once the application is out of alpha in order to post it. It will be the same format as what was done with the Recalls API - 

https://open.canada.ca/data/en/dataset/d38de914-c94c-429b-8ab1-8776c31643e3

**Comment by obrien-j** [comment]
Re-opening to provide a path forward for NRCan after handoff. Will unassign and move to un-scoped for post-handoff completion.

**Comment by sdkibb** [comment]
They won't be posting a static data set. They'll be putting a doc and inks to the live API. Create a new issue with an appropriate title once NRCan moves/creates it in their own repo.account. This doesn't belong here and isn't named properly.
